### ISSUE TITLE
QQ 登录页面作业反馈

### ISSUE THREAD

**Issue by twhy** [agui526/warriors#1]
完成的还不错，有一些地方需要改进。
1. 两个输入框不能四个角都是圆角。用户名是左上和右上圆角，密码是左下和右下是圆角。
```
#uname { border-radius: 4px 4px 0 0; }
#passwd { border-radisu: 0 0 4px 4px; }
```
2. 可以通过 `input::-webkit-input-placeholder { color: #aaa; }` 给 placeholder 设置字体颜色。
3. 一键登录按钮和登录按钮的样式是不一样的，要注意。
<img width="318" alt="qq" src="https://user-images.githubusercontent.com/7459812/27166074-d4351694-51ca-11e7-8d65-9d2f80e20d55.png">

**Comment by agui526** [comment]
updated
